#!/bin/csh -f
set supportedPythonVersions=(2 3)
set name=scripts
rm -f install.out

# run pylint to find egregious errors
# # this is optional, you can delete this line if you don't have pylint
pylint -E --disable=no-member $name.py

foreach vers ($supportedPythonVersions)

    # remove build directory from a previous install to assure a clean install
    rm -rf build

    which python$vers >& /dev/null
    if ($status == 0) then
        echo "Installing $name to Python$vers."
        python$vers setup.py install --quiet --user >>& install.out
        if ($status) then
            echo "Problems found, aborting (see install.out)"
            exit(1)
        endif
    else
        echo "Cannot install $name to Python$vers, it is not available."
    endif
end
